name: Deploy Chat2db Lambda to AWS

on:
  push:
    branches: [main]

env:
  ZIP_FILE_NAME: chat2db.zip
  S3_BUCKET: chat2db
  AWS_REGION: eu-north-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Package application
        run: |
          mkdir -p package
          pip install -r backend/requirements.txt -t package/
          cp -r backend/* package/
          cd package && zip -r ../$ZIP_FILE_NAME .
      

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp $ZIP_FILE_NAME s3://$S3_BUCKET/$ZIP_FILE_NAME

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file backend/cfn-template.yaml \
            --stack-name chat2db-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                FunctionName=chat2db \
                TableName=Chat2dbTokenUsage \
                S3BucketName=$S3_BUCKET \
                OpenaiApiKey=${{ secrets.OPENAI_API_KEY }} \
            --region  ${{ env.AWS_REGION }}
